# Generated by Django 2.0.4 on 2018-08-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20180809_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Sample summary ajsgsfujdwefbhgujndsfhujfnhbdfujefnhgrujkhurıjn', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='club.Post'),
        ),
    ]
